name: Keith Wegner
description: Founder & Software Engineer
url: https://keithwegner.github.io
baseurl: ""
permalink: /:title/

links:
  - label: GitHub
    url: https://github.com/keithwegner
  - label: LinkedIn
    url: https://www.linkedin.com/in/keithwegner/
    primary: true
  - label: Bestgate
    url: https://www.bestgateeng.com

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: :compressed

exclude:
  - LICENSE
  - README.md
